### ISSUE TITLE
Takes too long (18 secs)

### ISSUE THREAD

**Issue by alex-jitbit** [microsoft/setup-msbuild#2]
This action simply finds the path to msbuild using the `vswhere` tool - why on earth it's taking 18 seconds? Is it because of the slow file system on the Github-hosted runner?

**Comment by timheuer** [comment]
Acknowledging this issue.  I'll look into this with runner team.

**Comment by alex-jitbit** [comment]
@timheuer thanksa lot, appreciate! At the moment I'm simply hardcoding the path.

I suspect it's because of the overall file-system warm up in a "just booted" Azure instance

**Comment by heaths** [comment]
vswhere itself is very fast, but I also see times when building it that running it the first time encounters a full Windows Defender scan. While you may be right about the warm up, I wouldn't expect it to be this slow unless, perhaps, Defender is compounding that. For hosted agents, I wonder if Defender should maybe only run for the workspace directories. They are ephemeral, so it's not like another tenant could corrupt someone else's host.

**Comment by heaths** [comment]
While resolving an issue I was having fixing another bug, I found it's the globbing that is the problem. I had to move when the globbing happens for compatibility. vswhere returned a value almost right away, but the globbing (now done outside vswhere, since globbing in vswhere is pretty new in Visual Studio) took a while. On my dev machines with ssds, this only takes about 1s. I imagine the drive type/configuration of the hosts is more of a factor here.

An alternative would be the [older way](https://github.com/microsoft/vswhere/wiki/Find-MSBuild/62adac8eb22431fa91d94e03503d76d48a74939c). I'll make the changes in the PR I'm working on for #10.
