### ISSUE TITLE
Setting up to use cl.exe with CMake

### ISSUE THREAD

**Issue by starseeker** [microsoft/setup-msbuild#32]
Hi!  I'm attempting to use this to set up my environment for a github action using CMake, Ninja and cl.exe, but when I do the following:
```
 - name: Add msbuild to PATH
   uses: microsoft/setup-msbuild@v1.0.2
  
 - name: Configure
   run: |
      cmake -S . -B build -G Ninja -D CMAKE_C_COMPILER="cl.exe" -D CMAKE_CXX_COMPILER="cl.exe" -D CMAKE_BUILD_TYPE=Release
```
CMake reports that cl.exe is not in the path:

```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  The CMAKE_C_COMPILER:

    cl.exe

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
```

Do I need to take some additional steps to get cl.exe's location in the path?

Thanks for any assistance.

**Comment by starseeker** [comment]
Ah, I've now identified https://github.com/marketplace/actions/enable-developer-command-prompt which looks like it can do what I need for this use case - if setup-msbuild isn't intended to expose cl.exe directly this issue can be closed.

**Comment by timheuer** [comment]
Correct @starseeker, this is not meant for the VC toolset.

**Comment by hostilefork** [comment]
@timheuer - There seem to be several issues like this (["I tried to use NMAKE.exe, it didn't work"](https://github.com/microsoft/setup-msbuild/issues/43)... and I had the same problem.)

I believe this is caused by the specific language in the README, which starts with:

*"You know how handy that 'Visual Studio Developer Command Prompt' is on your local machine? And how it adds several things to PATH to allow you to just issue commands like msbuild or otherwise?"*

To which I thought "Yes, I know that is handy!"  It then says:

*"Use this action to setup similar flexibility in your Windows-based GitHub Actions runners."*

To which I think the natural response is to say "Ok, sold!" and try it...only to find that it only installs a path for msbuild.  The "Visual Studio Developer Command Prompt" does more.  So it does not seem like the right thing to compare to.

1. Could the README.md be edited to make it more clear that this does *not* do what the command prompt does?

2. The [`enable-developer-command-prompt`](https://github.com/marketplace/actions/enable-developer-command-prompt) seems be a good thing to link to after mentioning the Visual Studio Developer Command Prompt.  Although having it not be from the official MS account is a liability.  Perhaps the author could be convinced to let Microsoft take it over?

Sidenote: The other extension is working for me for CL and NMAKE...but I actually am getting what I think is the wrong link.exe from the enable-developer-command-prompt (/usr/bin/link ?) which signs seem to point to being a GNU linker.  It's complaining about `extra operand '/subsystem:console'`.  :-/

**Comment by Geod24** [comment]
Just to add that I ran into the same problem. Thought this action was right for me when I read the description, then my script couldn't find `cl.exe`. Looking at the name of the action, it's a bit more obvious, but the README is really misleading.
